# Generated by Django 5.2.7 on 2025-10-31 02:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                ("empresa", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "data_cadastro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                ("assunto", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contatos",
                        to="app_crm.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Oportunidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("prospeccao", "Prospecção"),
                            ("proposta", "Proposta"),
                            ("negociacao", "Negociação"),
                            ("fechado_ganho", "Fechado Ganho"),
                            ("fechado_perdido", "Fechado Perdido"),
                        ],
                        default="prospeccao",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oportunidades",
                        to="app_crm.cliente",
                    ),
                ),
            ],
        ),
    ]
