# Generated by Django 5.2.7 on 2025-11-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_crm", "0002_curso_avaliacaocurso"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioCredencial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=20, unique=True)),
                ("senha", models.CharField(max_length=128)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
    ]
