# Generated by Django 5.2.7 on 2025-11-01 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_crm", "0003_usuariocredencial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("bolsista", models.BooleanField(default=False)),
                ("profissao", models.CharField(max_length=100)),
                (
                    "horario",
                    models.CharField(
                        choices=[
                            ("manha", "Manhã"),
                            ("tarde", "Tarde"),
                            ("noite", "Noite"),
                            ("integral", "Integral"),
                            ("fins_semana", "Fins de Semana"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contato",
                    models.CharField(
                        choices=[
                            ("telefone", "Telefone"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "E-mail"),
                            ("presencial", "Presencial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interessados",
                        to="app_crm.curso",
                    ),
                ),
            ],
        ),
    ]
